# Generated by Django 5.2.3 on 2026-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homigram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
