# Generated by Django 5.2.3 on 2026-03-11 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homigram', '0002_alter_escrow_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('tenant', 'property')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='daily_fee',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='interest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='homigram.interest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='low_balance_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('cancelled_by_tenant', 'Cancelled by Tenant'), ('cancelled_by_landlord', 'Cancelled by Landlord'), ('expired', 'Expired - Insufficient Funds'), ('completed', 'Completed - Moved to Occupancy')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_active',
        ),
    ]
