# Generated by Django 5.2.3 on 2026-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homigram', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='amount_paid',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
