# Generated by Django 5.2.3 on 2026-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homigram', '0004_alter_inspection_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrow',
            old_name='total_rent',
            new_name='annual_rent',
        ),
        migrations.AddField(
            model_name='escrow',
            name='escrow_type',
            field=models.CharField(choices=[('occupancy', 'Occupancy Deposit'), ('reservation', 'Reservation Deposit')], default='available', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='offline_rent_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='reservation_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
