# Generated by Django 5.2.3 on 2026-03-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homigram', '0005_rename_total_rent_escrow_annual_rent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-paid_at']},
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
